<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="50" passed="30" failed="20" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-02-16T02:27:39 IST" name="Automation Test Suite" finished-at="2023-02-16T02:35:27 IST" duration-ms="468139">
    <groups>
      <group name="smoke">
        <method signature="TestLogin.verify_login_With_Valid_Credential()[pri:1, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" name="verify_login_With_Valid_Credential" class="com.tutorialsninja.qa.testCases.TestLogin"/>
        <method signature="TestRegister.verify_Registering_Mandatory_Field()[pri:1, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" name="verify_Registering_Mandatory_Field" class="com.tutorialsninja.qa.testCases.TestRegister"/>
      </group> <!-- smoke -->
    </groups>
    <test started-at="2023-02-16T02:27:39 IST" name="Automation Test cases" finished-at="2023-02-16T02:35:27 IST" duration-ms="468139">
      <class name="com.tutorialsninja.qa.testCases.TestLogin">
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:30:41 IST" name="initilization" finished-at="2023-02-16T02:30:46 IST" duration-ms="4641" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_login_With_Valid_Credential()[pri:1, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:30:46 IST" name="verify_login_With_Valid_Credential" finished-at="2023-02-16T02:30:48 IST" duration-ms="2547" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_login_With_Valid_Credential -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:30:48 IST" name="tearDown" finished-at="2023-02-16T02:30:49 IST" duration-ms="303" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:30:49 IST" name="initilization" finished-at="2023-02-16T02:30:54 IST" duration-ms="5270" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_login_With_InValid_Credential()[pri:2, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:30:54 IST" name="verify_login_With_InValid_Credential" finished-at="2023-02-16T02:30:56 IST" duration-ms="2119" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_login_With_InValid_Credential -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:30:56 IST" name="tearDown" finished-at="2023-02-16T02:30:56 IST" duration-ms="221" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:30:56 IST" name="initilization" finished-at="2023-02-16T02:31:02 IST" duration-ms="5374" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_login_With_Valid_password_invalid_userName()[pri:3, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:31:02 IST" name="verify_login_With_Valid_password_invalid_userName" finished-at="2023-02-16T02:31:05 IST" duration-ms="2833" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_login_With_Valid_password_invalid_userName -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:31:05 IST" name="tearDown" finished-at="2023-02-16T02:31:05 IST" duration-ms="475" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:31:05 IST" name="initilization" finished-at="2023-02-16T02:31:10 IST" duration-ms="5335" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_login_With_Valid_userName_invalid_password()[pri:4, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:31:10 IST" name="verify_login_With_Valid_userName_invalid_password" finished-at="2023-02-16T02:31:13 IST" duration-ms="2742" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_login_With_Valid_userName_invalid_password -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:31:13 IST" name="tearDown" finished-at="2023-02-16T02:31:13 IST" duration-ms="207" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:31:13 IST" name="initilization" finished-at="2023-02-16T02:31:19 IST" duration-ms="5458" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_login_Without_Credentials()[pri:5, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:31:19 IST" name="verify_login_Without_Credentials" finished-at="2023-02-16T02:31:21 IST" duration-ms="2164" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_login_Without_Credentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:31:21 IST" name="tearDown" finished-at="2023-02-16T02:31:21 IST" duration-ms="319" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:31:21 IST" name="initilization" finished-at="2023-02-16T02:31:27 IST" duration-ms="5645" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_login_Forgetten_Password()[pri:6, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:31:27 IST" name="verify_login_Forgetten_Password" finished-at="2023-02-16T02:31:28 IST" duration-ms="1178" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_login_Forgetten_Password -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:31:28 IST" name="tearDown" finished-at="2023-02-16T02:31:28 IST" duration-ms="247" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:31:28 IST" name="initilization" finished-at="2023-02-16T02:31:33 IST" duration-ms="4820" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_login_With_Valid_Credential_BrowserBack()[pri:9, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:31:33 IST" name="verify_login_With_Valid_Credential_BrowserBack" finished-at="2023-02-16T02:31:45 IST" duration-ms="11776" status="FAIL">
          <exception class="org.openqa.selenium.NoSuchElementException">
            <message>
              <![CDATA[no such element: Unable to locate element: {"method":"xpath","selector":"(//div[@class='well'])[2]/h2"}
  (Session info: MicrosoftEdge=110.0.1587.41)
For documentation on this error, please visit: https://selenium.dev/exceptions/#no_such_element
Build info: version: '4.6.0', revision: '79f1c02ae20'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.5'
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [f5c596ed2c0c6eb253cba202096dabea, findElement {using=xpath, value=(//div[@class='well'])[2]/h2}]
Capabilities {acceptInsecureCerts: false, browserName: msedge, browserVersion: 110.0.1587.41, ms:edgeOptions: {debuggerAddress: localhost:56803}, msedge: {msedgedriverVersion: 110.0.1587.41 (dec2c0803210..., userDataDir: C:\Users\Mahi\AppData\Local...}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:56803/devtoo..., se:cdpVersion: 110.0.1587.41, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: f5c596ed2c0c6eb253cba202096dabea]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"(//div[@class='well'])[2]/h2"}
  (Session info: MicrosoftEdge=110.0.1587.41)
For documentation on this error, please visit: https://selenium.dev/exceptions/#no_such_element
Build info: version: '4.6.0', revision: '79f1c02ae20'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.5'
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [f5c596ed2c0c6eb253cba202096dabea, findElement {using=xpath, value=(//div[@class='well'])[2]/h2}]
Capabilities {acceptInsecureCerts: false, browserName: msedge, browserVersion: 110.0.1587.41, ms:edgeOptions: {debuggerAddress: localhost:56803}, msedge: {msedgedriverVersion: 110.0.1587.41 (dec2c0803210..., userDataDir: C:\Users\Mahi\AppData\Local...}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:56803/devtoo..., se:cdpVersion: 110.0.1587.41, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: f5c596ed2c0c6eb253cba202096dabea
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:541)
at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:162)
at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:60)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:365)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:357)
at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:70)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:39)
at jdk.proxy2/jdk.proxy2.$Proxy15.getText(Unknown Source)
at com.tutorialsninja.qa.pageObjects.LoginPageObjects.returningCustomer_actual_text(LoginPageObjects.java:105)
at com.tutorialsninja.qa.testCases.TestLogin.verify_login_With_Valid_Credential_BrowserBack(TestLogin.java:114)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.NoSuchElementException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_login_With_Valid_Credential_BrowserBack -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:31:45 IST" name="tearDown" finished-at="2023-02-16T02:31:45 IST" duration-ms="320" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:31:45 IST" name="initilization" finished-at="2023-02-16T02:31:50 IST" duration-ms="4490" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_login_afterLogin_browserBack()[pri:10, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:31:50 IST" name="verify_login_afterLogin_browserBack" finished-at="2023-02-16T02:31:52 IST" duration-ms="2524" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Account Logout expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Account Logout expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at com.tutorialsninja.qa.testCases.TestLogin.verify_login_afterLogin_browserBack(TestLogin.java:134)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_login_afterLogin_browserBack -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:31:53 IST" name="tearDown" finished-at="2023-02-16T02:31:53 IST" duration-ms="175" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:31:53 IST" name="initilization" finished-at="2023-02-16T02:31:58 IST" duration-ms="5013" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_login_MultipleTime_Unsuccessful_attempt()[pri:11, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:31:58 IST" name="verify_login_MultipleTime_Unsuccessful_attempt" finished-at="2023-02-16T02:32:00 IST" duration-ms="2600" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.] but found []
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.tutorialsninja.qa.testCases.TestLogin.verify_login_MultipleTime_Unsuccessful_attempt(TestLogin.java:150)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_login_MultipleTime_Unsuccessful_attempt -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:32:01 IST" name="tearDown" finished-at="2023-02-16T02:32:01 IST" duration-ms="230" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:32:01 IST" name="initilization" finished-at="2023-02-16T02:32:06 IST" duration-ms="4933" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_login_MultipleTime_Unsuccessful_attempt()[pri:11, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:32:06 IST" name="verify_login_MultipleTime_Unsuccessful_attempt" finished-at="2023-02-16T02:32:07 IST" duration-ms="1467" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.] but found []
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.tutorialsninja.qa.testCases.TestLogin.verify_login_MultipleTime_Unsuccessful_attempt(TestLogin.java:150)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_login_MultipleTime_Unsuccessful_attempt -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:32:07 IST" name="tearDown" finished-at="2023-02-16T02:32:08 IST" duration-ms="246" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:32:08 IST" name="initilization" finished-at="2023-02-16T02:32:12 IST" duration-ms="4756" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_login_MultipleTime_Unsuccessful_attempt()[pri:11, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:32:12 IST" name="verify_login_MultipleTime_Unsuccessful_attempt" finished-at="2023-02-16T02:32:14 IST" duration-ms="1628" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.] but found []
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.tutorialsninja.qa.testCases.TestLogin.verify_login_MultipleTime_Unsuccessful_attempt(TestLogin.java:150)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_login_MultipleTime_Unsuccessful_attempt -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:32:14 IST" name="tearDown" finished-at="2023-02-16T02:32:14 IST" duration-ms="235" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:32:14 IST" name="initilization" finished-at="2023-02-16T02:32:20 IST" duration-ms="5222" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_login_MultipleTime_Unsuccessful_attempt()[pri:11, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:32:20 IST" name="verify_login_MultipleTime_Unsuccessful_attempt" finished-at="2023-02-16T02:32:21 IST" duration-ms="1517" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.] but found []
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.tutorialsninja.qa.testCases.TestLogin.verify_login_MultipleTime_Unsuccessful_attempt(TestLogin.java:150)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_login_MultipleTime_Unsuccessful_attempt -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:32:21 IST" name="tearDown" finished-at="2023-02-16T02:32:22 IST" duration-ms="283" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:32:22 IST" name="initilization" finished-at="2023-02-16T02:32:27 IST" duration-ms="4971" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_login_MultipleTime_Unsuccessful_attempt()[pri:11, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:32:27 IST" name="verify_login_MultipleTime_Unsuccessful_attempt" finished-at="2023-02-16T02:32:28 IST" duration-ms="1511" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.] but found []
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.tutorialsninja.qa.testCases.TestLogin.verify_login_MultipleTime_Unsuccessful_attempt(TestLogin.java:150)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_login_MultipleTime_Unsuccessful_attempt -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:32:28 IST" name="tearDown" finished-at="2023-02-16T02:32:29 IST" duration-ms="340" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:32:29 IST" name="initilization" finished-at="2023-02-16T02:32:34 IST" duration-ms="4938" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_login_MultipleTime_Unsuccessful_attempt()[pri:11, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:32:34 IST" name="verify_login_MultipleTime_Unsuccessful_attempt" finished-at="2023-02-16T02:32:35 IST" duration-ms="1625" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.] but found []
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.tutorialsninja.qa.testCases.TestLogin.verify_login_MultipleTime_Unsuccessful_attempt(TestLogin.java:150)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_login_MultipleTime_Unsuccessful_attempt -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:32:35 IST" name="tearDown" finished-at="2023-02-16T02:32:36 IST" duration-ms="220" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:32:36 IST" name="initilization" finished-at="2023-02-16T02:32:41 IST" duration-ms="5080" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_login_MultipleTime_Unsuccessful_attempt()[pri:11, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:32:41 IST" name="verify_login_MultipleTime_Unsuccessful_attempt" finished-at="2023-02-16T02:32:42 IST" duration-ms="1608" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.] but found []
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.tutorialsninja.qa.testCases.TestLogin.verify_login_MultipleTime_Unsuccessful_attempt(TestLogin.java:150)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_login_MultipleTime_Unsuccessful_attempt -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:32:42 IST" name="tearDown" finished-at="2023-02-16T02:32:43 IST" duration-ms="221" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:32:43 IST" name="initilization" finished-at="2023-02-16T02:32:47 IST" duration-ms="4781" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_login_MultipleTime_Unsuccessful_attempt()[pri:11, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:32:47 IST" name="verify_login_MultipleTime_Unsuccessful_attempt" finished-at="2023-02-16T02:32:49 IST" duration-ms="1541" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.] but found []
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.tutorialsninja.qa.testCases.TestLogin.verify_login_MultipleTime_Unsuccessful_attempt(TestLogin.java:150)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_login_MultipleTime_Unsuccessful_attempt -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:32:49 IST" name="tearDown" finished-at="2023-02-16T02:32:49 IST" duration-ms="294" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:32:49 IST" name="initilization" finished-at="2023-02-16T02:32:54 IST" duration-ms="4715" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_login_MultipleTime_Unsuccessful_attempt()[pri:11, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:32:54 IST" name="verify_login_MultipleTime_Unsuccessful_attempt" finished-at="2023-02-16T02:32:57 IST" duration-ms="2586" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.] but found []
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.tutorialsninja.qa.testCases.TestLogin.verify_login_MultipleTime_Unsuccessful_attempt(TestLogin.java:150)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_login_MultipleTime_Unsuccessful_attempt -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:32:57 IST" name="tearDown" finished-at="2023-02-16T02:32:57 IST" duration-ms="344" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:32:57 IST" name="initilization" finished-at="2023-02-16T02:33:02 IST" duration-ms="5084" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_login_MultipleTime_Unsuccessful_attempt()[pri:11, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:33:02 IST" name="verify_login_MultipleTime_Unsuccessful_attempt" finished-at="2023-02-16T02:33:04 IST" duration-ms="1591" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.] but found []
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.tutorialsninja.qa.testCases.TestLogin.verify_login_MultipleTime_Unsuccessful_attempt(TestLogin.java:150)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_login_MultipleTime_Unsuccessful_attempt -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:33:04 IST" name="tearDown" finished-at="2023-02-16T02:33:04 IST" duration-ms="238" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:33:04 IST" name="initilization" finished-at="2023-02-16T02:33:09 IST" duration-ms="4600" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_login_Copying_TEXT_PasswordFiled()[pri:12, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:33:09 IST" name="verify_login_Copying_TEXT_PasswordFiled" finished-at="2023-02-16T02:33:10 IST" duration-ms="1295" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_login_Copying_TEXT_PasswordFiled -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:33:10 IST" name="tearDown" finished-at="2023-02-16T02:33:10 IST" duration-ms="239" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:33:10 IST" name="initilization" finished-at="2023-02-16T02:33:15 IST" duration-ms="4915" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_login_Code_In_SourceCode_PasswordFiled()[pri:13, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:33:15 IST" name="verify_login_Code_In_SourceCode_PasswordFiled" finished-at="2023-02-16T02:33:17 IST" duration-ms="1785" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect [xyzabc123   ] but found [xyzabc123   ]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect [xyzabc123   ] but found [xyzabc123   ]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failEquals(Assert.java:1417)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:156)
at org.testng.Assert.assertNotEquals(Assert.java:2033)
at org.testng.Assert.assertNotEquals(Assert.java:2055)
at com.tutorialsninja.qa.testCases.TestLogin.verify_login_Code_In_SourceCode_PasswordFiled(TestLogin.java:174)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_login_Code_In_SourceCode_PasswordFiled -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:33:17 IST" name="tearDown" finished-at="2023-02-16T02:33:18 IST" duration-ms="237" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:33:18 IST" name="initilization" finished-at="2023-02-16T02:33:22 IST" duration-ms="4796" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_login_after_Changing_Password()[pri:14, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:33:22 IST" name="verify_login_after_Changing_Password" finished-at="2023-02-16T02:33:28 IST" duration-ms="5180" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_login_after_Changing_Password -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:33:28 IST" name="tearDown" finished-at="2023-02-16T02:33:28 IST" duration-ms="222" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:33:28 IST" name="initilization" finished-at="2023-02-16T02:33:33 IST" duration-ms="5337" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_login_able_to_navigate_to_otherPages()[pri:15, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:33:33 IST" name="verify_login_able_to_navigate_to_otherPages" finished-at="2023-02-16T02:33:36 IST" duration-ms="2843" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_login_able_to_navigate_to_otherPages -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:33:36 IST" name="tearDown" finished-at="2023-02-16T02:33:36 IST" duration-ms="238" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:33:36 IST" name="initilization" finished-at="2023-02-16T02:33:41 IST" duration-ms="5080" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_login_after_Changing_Password_and_Changing_toOriginal_password()[pri:16, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:33:41 IST" name="verify_login_after_Changing_Password_and_Changing_toOriginal_password" finished-at="2023-02-16T02:33:47 IST" depends-on-methods="com.tutorialsninja.qa.testCases.TestLogin.verify_login_after_Changing_Password" duration-ms="5678" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_login_after_Changing_Password_and_Changing_toOriginal_password -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogin@223d2c72]" started-at="2023-02-16T02:33:47 IST" name="tearDown" finished-at="2023-02-16T02:33:47 IST" duration-ms="247" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tutorialsninja.qa.testCases.TestLogin -->
      <class name="com.tutorialsninja.qa.testCases.TestForgetPassword">
        <test-method is-config="true" signature="initlization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestForgetPassword@436813f3]" started-at="2023-02-16T02:35:04 IST" name="initlization" finished-at="2023-02-16T02:35:10 IST" duration-ms="6517" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initlization -->
        <test-method signature="verify_forgetPassword_Withoutout_reset_but_IntitiateProcess()[pri:1, instance:com.tutorialsninja.qa.testCases.TestForgetPassword@436813f3]" started-at="2023-02-16T02:35:10 IST" name="verify_forgetPassword_Withoutout_reset_but_IntitiateProcess" finished-at="2023-02-16T02:35:12 IST" duration-ms="2003" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_forgetPassword_Withoutout_reset_but_IntitiateProcess -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestForgetPassword@436813f3]" started-at="2023-02-16T02:35:12 IST" name="tearDown" finished-at="2023-02-16T02:35:12 IST" duration-ms="275" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initlization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestForgetPassword@436813f3]" started-at="2023-02-16T02:35:12 IST" name="initlization" finished-at="2023-02-16T02:35:18 IST" duration-ms="5617" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initlization -->
        <test-method signature="verify_forgetPassword_With_nonRegistered_Account()[pri:2, instance:com.tutorialsninja.qa.testCases.TestForgetPassword@436813f3]" started-at="2023-02-16T02:35:18 IST" name="verify_forgetPassword_With_nonRegistered_Account" finished-at="2023-02-16T02:35:19 IST" duration-ms="1243" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_forgetPassword_With_nonRegistered_Account -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestForgetPassword@436813f3]" started-at="2023-02-16T02:35:19 IST" name="tearDown" finished-at="2023-02-16T02:35:20 IST" duration-ms="301" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initlization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestForgetPassword@436813f3]" started-at="2023-02-16T02:35:20 IST" name="initlization" finished-at="2023-02-16T02:35:25 IST" duration-ms="5695" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initlization -->
        <test-method signature="verify_forgetPassword_Without_providing_EmailAddress()[pri:3, instance:com.tutorialsninja.qa.testCases.TestForgetPassword@436813f3]" started-at="2023-02-16T02:35:25 IST" name="verify_forgetPassword_Without_providing_EmailAddress" finished-at="2023-02-16T02:35:26 IST" duration-ms="1162" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[E-Mail must be between 4 and 20 characters!' should be displayed for 'E-Mail Address' field expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: E-Mail must be between 4 and 20 characters!' should be displayed for 'E-Mail Address' field expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at com.tutorialsninja.qa.testCases.TestForgetPassword.verify_forgetPassword_Without_providing_EmailAddress(TestForgetPassword.java:69)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_forgetPassword_Without_providing_EmailAddress -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestForgetPassword@436813f3]" started-at="2023-02-16T02:35:27 IST" name="tearDown" finished-at="2023-02-16T02:35:27 IST" duration-ms="237" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tutorialsninja.qa.testCases.TestForgetPassword -->
      <class name="com.tutorialsninja.qa.testCases.TestLogout">
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogout@8f4ea7c]" started-at="2023-02-16T02:33:47 IST" name="initilization" finished-at="2023-02-16T02:33:53 IST" duration-ms="6273" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_Logout_By_LoggingOut_From_MyAccount_Dropdown()[pri:1, instance:com.tutorialsninja.qa.testCases.TestLogout@8f4ea7c]" started-at="2023-02-16T02:33:53 IST" name="verify_Logout_By_LoggingOut_From_MyAccount_Dropdown" finished-at="2023-02-16T02:33:56 IST" duration-ms="2933" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_Logout_By_LoggingOut_From_MyAccount_Dropdown -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogout@8f4ea7c]" started-at="2023-02-16T02:33:56 IST" name="tearDown" finished-at="2023-02-16T02:33:57 IST" duration-ms="305" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogout@8f4ea7c]" started-at="2023-02-16T02:33:57 IST" name="initilization" finished-at="2023-02-16T02:34:03 IST" duration-ms="6510" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_Logout_By_LoggingOut_From_LogoutOption_OnPage()[pri:2, instance:com.tutorialsninja.qa.testCases.TestLogout@8f4ea7c]" started-at="2023-02-16T02:34:03 IST" name="verify_Logout_By_LoggingOut_From_LogoutOption_OnPage" finished-at="2023-02-16T02:34:06 IST" duration-ms="2537" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_Logout_By_LoggingOut_From_LogoutOption_OnPage -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogout@8f4ea7c]" started-at="2023-02-16T02:34:06 IST" name="tearDown" finished-at="2023-02-16T02:34:06 IST" duration-ms="276" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogout@8f4ea7c]" started-at="2023-02-16T02:34:06 IST" name="initilization" finished-at="2023-02-16T02:34:13 IST" duration-ms="6664" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_Logout_By_LoggingOut_And_BrowsingBack()[pri:3, instance:com.tutorialsninja.qa.testCases.TestLogout@8f4ea7c]" started-at="2023-02-16T02:34:13 IST" name="verify_Logout_By_LoggingOut_And_BrowsingBack" finished-at="2023-02-16T02:34:15 IST" duration-ms="2529" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Account Logout] but found [My Account]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Account Logout] but found [My Account]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.tutorialsninja.qa.testCases.TestLogout.verify_Logout_By_LoggingOut_And_BrowsingBack(TestLogout.java:64)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_Logout_By_LoggingOut_And_BrowsingBack -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogout@8f4ea7c]" started-at="2023-02-16T02:34:15 IST" name="tearDown" finished-at="2023-02-16T02:34:16 IST" duration-ms="364" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogout@8f4ea7c]" started-at="2023-02-16T02:34:16 IST" name="initilization" finished-at="2023-02-16T02:34:22 IST" duration-ms="5988" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_Logout_Option_NotDisplayed_BeforeLogin_Account_Drodown()[pri:4, instance:com.tutorialsninja.qa.testCases.TestLogout@8f4ea7c]" started-at="2023-02-16T02:34:22 IST" name="verify_Logout_Option_NotDisplayed_BeforeLogin_Account_Drodown" finished-at="2023-02-16T02:34:32 IST" duration-ms="10204" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_Logout_Option_NotDisplayed_BeforeLogin_Account_Drodown -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogout@8f4ea7c]" started-at="2023-02-16T02:34:32 IST" name="tearDown" finished-at="2023-02-16T02:34:32 IST" duration-ms="294" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogout@8f4ea7c]" started-at="2023-02-16T02:34:32 IST" name="initilization" finished-at="2023-02-16T02:34:39 IST" duration-ms="6431" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_Logout_Option_NotDisplayed_BeforeLogin_UnderRight_Column()[pri:5, instance:com.tutorialsninja.qa.testCases.TestLogout@8f4ea7c]" started-at="2023-02-16T02:34:39 IST" name="verify_Logout_Option_NotDisplayed_BeforeLogin_UnderRight_Column" finished-at="2023-02-16T02:34:49 IST" duration-ms="10035" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_Logout_Option_NotDisplayed_BeforeLogin_UnderRight_Column -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogout@8f4ea7c]" started-at="2023-02-16T02:34:49 IST" name="tearDown" finished-at="2023-02-16T02:34:49 IST" duration-ms="204" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogout@8f4ea7c]" started-at="2023-02-16T02:34:49 IST" name="initilization" finished-at="2023-02-16T02:34:55 IST" duration-ms="5620" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_Logout_AfterLogout_FromOneAccount_AnotherAccount()[pri:6, instance:com.tutorialsninja.qa.testCases.TestLogout@8f4ea7c]" started-at="2023-02-16T02:34:55 IST" name="verify_Logout_AfterLogout_FromOneAccount_AnotherAccount" finished-at="2023-02-16T02:34:57 IST" duration-ms="2604" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_Logout_AfterLogout_FromOneAccount_AnotherAccount -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestLogout@8f4ea7c]" started-at="2023-02-16T02:34:57 IST" name="tearDown" finished-at="2023-02-16T02:35:04 IST" duration-ms="6424" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tutorialsninja.qa.testCases.TestLogout -->
      <class name="com.tutorialsninja.qa.testCases.TestRegister">
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:27:39 IST" name="initilization" finished-at="2023-02-16T02:27:55 IST" duration-ms="15928" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_Registering_Mandatory_Field()[pri:1, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:27:55 IST" name="verify_Registering_Mandatory_Field" finished-at="2023-02-16T02:27:59 IST" duration-ms="3790" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_Registering_Mandatory_Field -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:27:59 IST" name="tearDown" finished-at="2023-02-16T02:27:59 IST" duration-ms="277" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:27:59 IST" name="initilization" finished-at="2023-02-16T02:28:05 IST" duration-ms="5271" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_Registering_BY_Providing_All_Fileds()[pri:2, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:28:05 IST" name="verify_Registering_BY_Providing_All_Fileds" finished-at="2023-02-16T02:28:08 IST" duration-ms="3777" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_Registering_BY_Providing_All_Fileds -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:28:08 IST" name="tearDown" finished-at="2023-02-16T02:28:09 IST" duration-ms="306" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:28:09 IST" name="initilization" finished-at="2023-02-16T02:28:15 IST" duration-ms="5874" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_Notification_BY_NotProviding_All_Fileds_BySubmiting()[pri:3, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:28:15 IST" name="verify_Notification_BY_NotProviding_All_Fileds_BySubmiting" finished-at="2023-02-16T02:28:17 IST" duration-ms="1863" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_Notification_BY_NotProviding_All_Fileds_BySubmiting -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:28:17 IST" name="tearDown" finished-at="2023-02-16T02:28:17 IST" duration-ms="285" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:28:17 IST" name="initilization" finished-at="2023-02-16T02:28:23 IST" duration-ms="5981" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_Registering_Newsletter_NO()[pri:4, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:28:23 IST" name="verify_Registering_Newsletter_NO" finished-at="2023-02-16T02:28:27 IST" duration-ms="3822" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_Registering_Newsletter_NO -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:28:27 IST" name="tearDown" finished-at="2023-02-16T02:28:27 IST" duration-ms="272" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:28:27 IST" name="initilization" finished-at="2023-02-16T02:28:34 IST" duration-ms="6856" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_Registering_Newsletter_YES()[pri:5, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:28:34 IST" name="verify_Registering_Newsletter_YES" finished-at="2023-02-16T02:28:37 IST" duration-ms="3575" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_Registering_Newsletter_YES -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:28:37 IST" name="tearDown" finished-at="2023-02-16T02:28:38 IST" duration-ms="525" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:28:38 IST" name="initilization" finished-at="2023-02-16T02:28:44 IST" duration-ms="5906" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_Registering_By_Different_Pass_con_pass()[pri:6, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:28:44 IST" name="verify_Registering_By_Different_Pass_con_pass" finished-at="2023-02-16T02:28:47 IST" duration-ms="3519" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_Registering_By_Different_Pass_con_pass -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:28:47 IST" name="tearDown" finished-at="2023-02-16T02:28:48 IST" duration-ms="245" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:28:48 IST" name="initilization" finished-at="2023-02-16T02:28:54 IST" duration-ms="6910" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_Registering_By_Existing_Account()[pri:7, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:28:54 IST" name="verify_Registering_By_Existing_Account" finished-at="2023-02-16T02:28:58 IST" duration-ms="3886" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_Registering_By_Existing_Account -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:28:58 IST" name="tearDown" finished-at="2023-02-16T02:28:59 IST" duration-ms="253" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:29:00 IST" name="initilization" finished-at="2023-02-16T02:29:05 IST" duration-ms="4936" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_Registering_By_Invalid_Email(java.lang.String,java.lang.String)[pri:8, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:29:05 IST" name="verify_Registering_By_Invalid_Email" data-provider="getData" finished-at="2023-02-16T02:29:07 IST" duration-ms="2652" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[test]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[12345]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_Registering_By_Invalid_Email -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:29:07 IST" name="tearDown" finished-at="2023-02-16T02:29:08 IST" duration-ms="389" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:29:08 IST" name="initilization" finished-at="2023-02-16T02:29:13 IST" duration-ms="5288" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_Registering_By_Invalid_Email(java.lang.String,java.lang.String)[pri:8, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:29:13 IST" name="verify_Registering_By_Invalid_Email" data-provider="getData" finished-at="2023-02-16T02:29:15 IST" duration-ms="2006" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[test@]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[12345]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_Registering_By_Invalid_Email -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:29:15 IST" name="tearDown" finished-at="2023-02-16T02:29:15 IST" duration-ms="232" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:29:15 IST" name="initilization" finished-at="2023-02-16T02:29:20 IST" duration-ms="4989" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_Registering_By_Invalid_Email(java.lang.String,java.lang.String)[pri:8, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:29:20 IST" name="verify_Registering_By_Invalid_Email" data-provider="getData" finished-at="2023-02-16T02:29:23 IST" duration-ms="2286" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[test@gmail.]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[12345]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_Registering_By_Invalid_Email -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:29:23 IST" name="tearDown" finished-at="2023-02-16T02:29:23 IST" duration-ms="282" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:29:23 IST" name="initilization" finished-at="2023-02-16T02:29:29 IST" duration-ms="5735" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_Registering_By_Invalid_Phone(java.lang.String)[pri:9, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:29:29 IST" name="verify_Registering_By_Invalid_Phone" data-provider="getTelephoneData" finished-at="2023-02-16T02:29:31 IST" duration-ms="2567" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[111]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at com.tutorialsninja.qa.testCases.TestRegister.verify_Registering_By_Invalid_Phone(TestRegister.java:192)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_Registering_By_Invalid_Phone -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:29:31 IST" name="tearDown" finished-at="2023-02-16T02:29:32 IST" duration-ms="222" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:29:32 IST" name="initilization" finished-at="2023-02-16T02:29:36 IST" duration-ms="4699" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_Registering_By_Invalid_Phone(java.lang.String)[pri:9, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:29:36 IST" name="verify_Registering_By_Invalid_Phone" data-provider="getTelephoneData" finished-at="2023-02-16T02:29:39 IST" duration-ms="2999" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[abcde]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at com.tutorialsninja.qa.testCases.TestRegister.verify_Registering_By_Invalid_Phone(TestRegister.java:192)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_Registering_By_Invalid_Phone -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:29:40 IST" name="tearDown" finished-at="2023-02-16T02:29:40 IST" duration-ms="274" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:29:40 IST" name="initilization" finished-at="2023-02-16T02:29:45 IST" duration-ms="4941" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_Registering_With_Space_Field()[pri:10, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:29:45 IST" name="verify_Registering_With_Space_Field" finished-at="2023-02-16T02:29:47 IST" duration-ms="2657" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Telephone must be between 3 and 32 characters!] but found [Password]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Telephone must be between 3 and 32 characters!] but found [Password]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.tutorialsninja.qa.testCases.TestRegister.verify_Registering_With_Space_Field(TestRegister.java:222)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_Registering_With_Space_Field -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:29:48 IST" name="tearDown" finished-at="2023-02-16T02:29:48 IST" duration-ms="231" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:29:48 IST" name="initilization" finished-at="2023-02-16T02:29:53 IST" duration-ms="5061" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_Registering_Complexity_Password()[pri:11, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:29:53 IST" name="verify_Registering_Complexity_Password" finished-at="2023-02-16T02:30:06 IST" duration-ms="12664" status="FAIL">
          <exception class="org.openqa.selenium.NoSuchElementException">
            <message>
              <![CDATA[no such element: Unable to locate element: {"method":"xpath","selector":"//input[@id='input-password']/following::div[1]"}
  (Session info: MicrosoftEdge=110.0.1587.41)
For documentation on this error, please visit: https://selenium.dev/exceptions/#no_such_element
Build info: version: '4.6.0', revision: '79f1c02ae20'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.5'
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [1c452d371543aec88935f1aad1256c07, findElement {using=xpath, value=//input[@id='input-password']/following::div[1]}]
Capabilities {acceptInsecureCerts: false, browserName: msedge, browserVersion: 110.0.1587.41, ms:edgeOptions: {debuggerAddress: localhost:56271}, msedge: {msedgedriverVersion: 110.0.1587.41 (dec2c0803210..., userDataDir: C:\Users\Mahi\AppData\Local...}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:56271/devtoo..., se:cdpVersion: 110.0.1587.41, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 1c452d371543aec88935f1aad1256c07]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@id='input-password']/following::div[1]"}
  (Session info: MicrosoftEdge=110.0.1587.41)
For documentation on this error, please visit: https://selenium.dev/exceptions/#no_such_element
Build info: version: '4.6.0', revision: '79f1c02ae20'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.5'
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [1c452d371543aec88935f1aad1256c07, findElement {using=xpath, value=//input[@id='input-password']/following::div[1]}]
Capabilities {acceptInsecureCerts: false, browserName: msedge, browserVersion: 110.0.1587.41, ms:edgeOptions: {debuggerAddress: localhost:56271}, msedge: {msedgedriverVersion: 110.0.1587.41 (dec2c0803210..., userDataDir: C:\Users\Mahi\AppData\Local...}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:56271/devtoo..., se:cdpVersion: 110.0.1587.41, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 1c452d371543aec88935f1aad1256c07
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:541)
at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:162)
at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:60)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:365)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:357)
at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:70)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:39)
at jdk.proxy2/jdk.proxy2.$Proxy15.getText(Unknown Source)
at com.tutorialsninja.qa.pageObjects.RegisterPageObjects.password_actual_WarningMessage(RegisterPageObjects.java:88)
at com.tutorialsninja.qa.testCases.TestRegister.verify_Registering_Complexity_Password(TestRegister.java:243)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.NoSuchElementException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_Registering_Complexity_Password -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:30:06 IST" name="tearDown" finished-at="2023-02-16T02:30:06 IST" duration-ms="254" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:30:06 IST" name="initilization" finished-at="2023-02-16T02:30:11 IST" duration-ms="5040" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_Registering_Spaces_Trimmed()[pri:12, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:30:11 IST" name="verify_Registering_Spaces_Trimmed" finished-at="2023-02-16T02:30:14 IST" duration-ms="2967" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect [    test    ] but found [    test    ]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect [    test    ] but found [    test    ]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failEquals(Assert.java:1417)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:156)
at org.testng.Assert.assertNotEquals(Assert.java:2033)
at org.testng.Assert.assertNotEquals(Assert.java:2055)
at com.tutorialsninja.qa.testCases.TestRegister.verify_Registering_Spaces_Trimmed(TestRegister.java:261)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_Registering_Spaces_Trimmed -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:30:14 IST" name="tearDown" finished-at="2023-02-16T02:30:14 IST" duration-ms="259" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:30:14 IST" name="initilization" finished-at="2023-02-16T02:30:19 IST" duration-ms="5008" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_Registering_PrivacyPolicy_isSelected()[pri:13, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:30:19 IST" name="verify_Registering_PrivacyPolicy_isSelected" finished-at="2023-02-16T02:30:20 IST" duration-ms="931" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_Registering_PrivacyPolicy_isSelected -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:30:20 IST" name="tearDown" finished-at="2023-02-16T02:30:21 IST" duration-ms="241" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:30:21 IST" name="initilization" finished-at="2023-02-16T02:30:25 IST" duration-ms="4413" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_Registering_PrivacyPolicy_Without_Selecting()[pri:14, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:30:25 IST" name="verify_Registering_PrivacyPolicy_Without_Selecting" finished-at="2023-02-16T02:30:32 IST" duration-ms="7406" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_Registering_PrivacyPolicy_Without_Selecting -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:30:32 IST" name="tearDown" finished-at="2023-02-16T02:30:33 IST" duration-ms="221" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initilization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:30:33 IST" name="initilization" finished-at="2023-02-16T02:30:38 IST" duration-ms="5264" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method signature="verify_Registering_enterPassword_WithoutConfirmPassword()[pri:15, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:30:38 IST" name="verify_Registering_enterPassword_WithoutConfirmPassword" finished-at="2023-02-16T02:30:41 IST" duration-ms="3083" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_Registering_enterPassword_WithoutConfirmPassword -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestRegister@6356695f]" started-at="2023-02-16T02:30:41 IST" name="tearDown" finished-at="2023-02-16T02:30:41 IST" duration-ms="248" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tutorialsninja.qa.testCases.TestRegister -->
    </test> <!-- Automation Test cases -->
  </suite> <!-- Automation Test Suite -->
</testng-results>
