<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="3" total="4" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-02-21T15:25:06 IST" name="Default suite" finished-at="2023-02-21T15:25:19 IST" duration-ms="12680">
    <groups>
      <group name="smoke">
        <method signature="TestForgetPassword.verify_forgetPassword_User_able_to_restore_password()[pri:1, instance:com.tutorialsninja.qa.testCases.TestForgetPassword@3f183caa]" name="verify_forgetPassword_User_able_to_restore_password" class="com.tutorialsninja.qa.testCases.TestForgetPassword"/>
      </group> <!-- smoke -->
    </groups>
    <test started-at="2023-02-21T15:25:06 IST" name="Default test" finished-at="2023-02-21T15:25:19 IST" duration-ms="12680">
      <class name="com.tutorialsninja.qa.testCases.TestForgetPassword">
        <test-method is-config="true" signature="initlization()[pri:0, instance:com.tutorialsninja.qa.testCases.TestForgetPassword@3f183caa]" started-at="2023-02-21T15:25:06 IST" name="initlization" finished-at="2023-02-21T15:25:16 IST" duration-ms="10009" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initlization -->
        <test-method signature="verify_forgetPassword_User_able_to_restore_password()[pri:1, instance:com.tutorialsninja.qa.testCases.TestForgetPassword@3f183caa]" started-at="2023-02-21T15:25:16 IST" name="verify_forgetPassword_User_able_to_restore_password" finished-at="2023-02-21T15:25:19 IST" duration-ms="2150" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at com.tutorialsninja.qa.testCases.TestForgetPassword.verify_forgetPassword_User_able_to_restore_password(TestForgetPassword.java:74)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_forgetPassword_User_able_to_restore_password -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tutorialsninja.qa.testCases.TestForgetPassword@3f183caa]" started-at="2023-02-21T15:25:19 IST" name="tearDown" finished-at="2023-02-21T15:25:19 IST" duration-ms="398" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tutorialsninja.qa.testCases.TestForgetPassword -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
